### ISSUE TITLE
the meaning of integral_zero_point

### ISSUE THREAD

**Issue by andeyeluguo** [clevercool/SQuant#11]
Great job, I am studying the code. But Still can not work out some questions.
### what's the meaning of signed which is always true.
https://github.com/clevercool/SQuant/blob/7218eb84a68e5eaae72ca8c43da38285c0de1d77/quant_affine.py#L103

### What's more, the meaning of integral_zero_point whose value is always true also confuses me .
https://github.com/clevercool/SQuant/blob/7218eb84a68e5eaae72ca8c43da38285c0de1d77/quant_affine.py#L98

### how can I understand this line
https://github.com/clevercool/SQuant/blob/7218eb84a68e5eaae72ca8c43da38285c0de1d77/quant_modules.py#L212

**Comment by clevercool** [comment]
Hi, thanks for your attention.

For the former two questions:
First, you may notice the file ```quanti_affine.py``` is precisely the original code from [ZeroQ](https://github.com/amirgholami/ZeroQ/blob/master/classification/utils/quantization_utils/quant_utils.py). We maintained its license and codes without any modification.

For the issue about ``` signed```, we also consider it a minor bug, which will NOT impact the accuracy. We adopt the asymmetric quantization method. The zero point is just the offset for the quantization grid. For example, if a tensor has the range of [0, 15], the zero point 8 only moves it to [-8, 7] to address the signed integer. And that does not influence the final quantization result after the [dequantization function](https://github.com/clevercool/SQuant/blob/9cc77fc2953629386c0ea985ae54bf6f28bfd3f9/quant_affine.py#L134).

By the way, I have fixed this bug, and you can refer to the updated code.

For the issue of ```integral_zero_point ```, it will round the zero point to an integer for practical implementation for INT quantization.

For the last question, it's a magic number. The signed activation has a broader range than the unsigned activation. Therefore, we need narrow the scope for quantization to increase the resolution. That is inspired by [ACIQ](https://github.com/submission2019/AnalyticalScaleForIntegerQuantization/blob/3246ee8cbfb747d7ef821c8cecc50283a73eaf92/pytorch_quantizer/quantization/qtypes/int_quantizer.py#L10). Others (ZeroQ, GDFQ) framework does NOT quantize the signed activation.

**Comment by andeyeluguo** [comment]
Thank you for you reply. I have another question.
https://github.com/clevercool/SQuant/blob/9cc77fc2953629386c0ea985ae54bf6f28bfd3f9/quant_modules.py#L194
I found some tensor may raise this error, I don't know why this happens.
Is there some idea to fix this problem? Thanks.

**Comment by clevercool** [comment]
I have revised this issue [here](https://github.com/clevercool/SQuant/issues/9).
