### ISSUE TITLE
SQuant+MSE ？

### ISSUE THREAD

**Issue by scxs1388** [clevercool/SQuant#12]
Hi,
I reimplemented SQuant in my code.
The result for ResNet-18 (top1 acc: 71.47) w4a32 quantization is 69.734%, it works fine.

But when I combined it with MSE to test the orthogonality,
the result becomes **65.888%**, which does not match the result (**70.12%**) according to the [review page](https://openreview.net/forum?id=JXhROKNZzOc) of your paper.

My code about MSE grid-search part was implemented based on open source code [MQBench](https://github.com/ModelTC/MQBench/blob/main/mqbench/observer.py#L478), not based on ACIQ.
I'm not sure what is the key to the problem.

So can you please provide more details about your experiment about SQuant+MSE？

Thank you.

**Comment by clevercool** [comment]
SQuant is a post-training quantization. It is sensitive to the quantization range. It needs a wider range than QAT, which the MQBench adopts.
You may notice there is a parameter "iter", which can determine the MSE search range in [20%, 100%].
I advise you can set the iter to 20 and make the search range [80%, 100%] max. It may work for SQuant.

There are many tricks for MSE search.
So, for convenience, our paper didn't include the MSE search results.

**Comment by scxs1388** [comment]
Thanks, you are right.

The top1-acc did increase from 65.88% to 68.27% after I set the iter to 20.
I also narrowed the search space to [90%, 100%] max and the result was even better (69.22%).

However, I still cannot reach your reported result 70.12%. How can I improve this?

**Comment by clevercool** [comment]
Is the function per-channel or per-tensor MSE search?

**Comment by scxs1388** [comment]
per-channel
