### ISSUE TITLE
What is the cuda version required to compile the qaunt_cuda extension?

### ISSUE THREAD

**Issue by mpjunaid** [clevercool/SQuant#4]
![Quant_cuda](https://user-images.githubusercontent.com/22269568/175015689-15cc0684-1172-4981-a3d2-241727e8c1cc.jpeg)
I get the following error from the image while pip install ./squant-kernel

My cuda version :11.1

**Comment by clevercool** [comment]
CUDA 11.1 is OK.
Did the Cuda toolkit install correctly？
Please follow the README to set.
`conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c nvidia`

**Comment by mpjunaid** [comment]
Thank you.
The conda install was installing wrong files. I dont know why. But checking all the installation and correcting it fixed the error.
