### ISSUE TITLE
Better accuracy?

### ISSUE THREAD

**Issue by lingffff** [clevercool/SQuant#5]
I just run
```bash
python -u main.py --model resnet18 --mode squant -wb 4 -ab 4  -s 12
```
but got **Final accuracy: 68.414**, higher than the result in your paper(66.14), 
is this correct?

**Comment by lingffff** [comment]
and Final accuracy: 72.324 for W6A6

**Comment by clevercool** [comment]
Actually, I think a possible reason is that you installed a newer version of ```pytorchcv```.
To conduct a fair comparison, the experiments are with ```pytorchcvv==0.0.51```.

I also updated the rounding function [here](https://github.com/clevercool/SQuant/blob/3cd893370fa46e36579147816fde69e38f819596/quant_modules.py#L111).
You can use this [commit](https://github.com/clevercool/SQuant/tree/2caa0f70a5130906ae31be8c275b6f745dc02de2) version to reproduce the paper result.

**Comment by lingffff** [comment]
Oh yes, I use pytorchcv==0.0.67. 
I will check the newer rounding function.
BTW, why newer version of pytorchcv can improve acc?

**Comment by clevercool** [comment]
Because the newer model checkpoints of newer pytorchcv have higher accuracy.

**Comment by lingffff** [comment]
You mean original float model?

**Comment by clevercool** [comment]
> You mean original float model?

Yes, you can verify it with flag ```--mode base```.

**Comment by lingffff** [comment]
okay, thanks a lot.
