### ISSUE TITLE
Whitepaper clarifications

### ISSUE THREAD

**Issue by gcunhase** [clevercool/SQuant#6]
Dear authors,

Can you please help clarify/explain the following items from your [whitepaper](https://openreview.net/forum?id=JXhROKNZzOc):
1. How do you conclude that _"SQuant-E is essentially the rounding method when r_e=0.5"_ (page 5, Subsection "Sub-item Analysis")? In other words, how does Eq. 9 ( $|\Delta \hat{W}| \leq r_e = 0.5$ ) result in the rounding method?
2. How does relaxing the $r_e$ constraint to 1.0 help satisfying $r_k=0.5$ (page 5, Subsection "Relaxation")?
3. How did you come up with the decomposition in Figure 1 ( $H \approx E + K + C$ )? In other words, how did you achieve the decomposition in Algorithm 3?

Thank you!

**Comment by clevercool** [comment]
First, the premise of all conclusions is that the numbers need to quantize to integer grids. Such as, the number 1.3 should only quantize to 1.0, 2.0, 3.0... and must NOT be quantized to 1.2, 1.4.

For the first issue, it is obvious that Eq. 9 ( $|\Delta \hat{W}| \leq r_e = 0.5$ ) is exactly the rounding method. $\Delta \hat{W}$ is the perturbation of weight before and after quantization. $|\Delta \hat{W}| \leq 0.5$ literally means round the number to the nearest integer number under the premise. For example, 1.3 can only be quantized to 1.0 with $|\Delta \hat{W}| = 0.3 \leq 0.5$.  And rounding is essentially for the quantization.

**Comment by clevercool** [comment]
For the second issue, when $r_e = 0.5$, the number can only employ the rounding policy. For example, 1.3 can only be quantized to 1.0 and can not be 2.0, which violates the   $|\Delta \hat{W}| \leq 0.5$ and $|\Delta \hat{W}| = 0.7$. Therefore, we need to relax the constraint to 1.0 to make the SQuant-K optimization available. Otherwise, SQuant-K can not be optimized because the $|\Delta \hat{W}| \leq 0.5$ is only the rounding method. (1.3 can not flip to 2.0).

**Comment by clevercool** [comment]
For the third issue, I design many experiments to find the best way to decompose the Hessian matrix. The final result is the way shown in Algo. 3.

**Comment by clevercool** [comment]
> 

The Algo. 2 explains what $k$ is (Line 2-4) and how are $k$ elements chosen(Line 5-6).
Ant Appendix B.2 explains why it should be Top-K.

**Comment by gcunhase** [comment]
Lines 5-6 say _"Indices of k largest perturbations"_, but it doesn't specify the value of k or how that is chosen... Is the $k$ chosen empirically?

The only mention I could find of that is in the last page of the paper _"SQuant-C only requires a tiny top-k number, such as k=32, to satisfy all cases. [...] SQuant-K only needs k=4 [...]"_. However, this seems to contradict the "Flip Algorithm" section (page 6), which says _"SQuant-C flips only one element in each kernel"_. Does that mean that SQuant-C has k=1 here?

**Comment by clevercool** [comment]
Line 2-4 of Algo. 2 explains how the value of k is chosen.
The $k$ is $=\lfloor |e| \rceil$ , where $e$ is the accumulated perturbation.
Please see it again.

**Comment by clevercool** [comment]
"SQuant-C flips only one element in each kernel" does NOT mean SQuant-C has k = 1.
One element in each kernel is maintaining a lower perturbation for kernel-wise SQuant-K.
However, it does NOT influence the total number of flipping number of channel.
SQuant-C is channel-wise optimization. There are many kernels in one channel.
Therefore, SQuant-C's k is also determined by the kernel perturbation, whose update process presents in Appendix B.3.
